// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchImage(arg1) {
  return window['go']['main']['App']['FetchImage'](arg1);
}

export function Request(arg1) {
  return window['go']['main']['App']['Request'](arg1);
}
