// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function FetchImage(arg1:string):Promise<app.ImageResponse>;

export function Request(arg1:app.HTTPRequest):Promise<app.HTTPResponse>;
